### ISSUE TITLE
[BUG] - Seems to be broken with vue 3.5

### ISSUE THREAD

**Issue by johnwc** [unplugin/unplugin-vue-ce#147]
### Describe the bug

With the latest release of 3.5, there is now an error when building components.

```
Building for production...C:\App\src\SiteWidget\node_modules\@unplugin-vue-ce\sub-style\index.cjs:110
  if (isApplyStylesIdentifier && isVueElementIdentifier && isBaseClassIdentifier && node.type === "CallExpression" && node.callee.type === "MemberExpression" && node.callee.property.name === "appendChild" && node.callee.object.property.name === "shadowRoot") {

TypeError: Cannot read properties of undefined (reading 'name')
    at injectApiCustomElement (C:\App\src\SiteWidget\node_modules\@unplugin-vue-ce\sub-style\index.cjs:110:237)
    at Object.enter (C:\App\src\SiteWidget\node_modules\@unplugin-vue-ce\sub-style\index.cjs:146:7)
    at d.visit (C:\App\src\SiteWidget\node_modules\estree-walker-ts\index.cjs:1:1360)
    at d.visit (C:\App\src\SiteWidget\node_modules\estree-walker-ts\index.cjs:1:1794)
    at d.visit (C:\App\src\SiteWidget\node_modules\estree-walker-ts\index.cjs:1:1756)
    at d.visit (C:\App\src\SiteWidget\node_modules\estree-walker-ts\index.cjs:1:1794)
    at d.visit (C:\App\src\SiteWidget\node_modules\estree-walker-ts\index.cjs:1:1756)
    at d.visit (C:\App\src\SiteWidget\node_modules\estree-walker-ts\index.cjs:1:1794)
    at x (C:\App\src\SiteWidget\node_modules\estree-walker-ts\index.cjs:1:3444)
    at injectVueRuntime (C:\App\src\SiteWidget\node_modules\@unplugin-vue-ce\sub-style\index.cjs:134:36)

Node.js v21.7.3
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/unplugin/unplugin-vue-ce/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a unplugin-vue-ce issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baiwusanyu-c** [comment]
I am glad that Vue 3.5 supports more features of custom elements. This repository should have completed its mission (a transitional solution before Vue supports more features for custom elements), so this repository should not support 3.5.
